spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/ai_platform
    username: root
    password: 123456

  # redis 配置
  redis:
    port: 6379
    host: localhost
    database: 0

  mail:
    host: #发送邮件服务器
    password: #密码
    username: #你的邮箱
    protocol: smtp
      properties:
        mail:
          smtp:
            auth: true
            socketFactory:
              port: 465
              class: javax.net.ssl.SSLSocketFactory
              fallback: false
            starttls:
              enable: true
              required: true

  rabbitmq:
    host: #你的地址
    port: 5672
    username: #用户名
    password: #密码
  elasticsearch:
    uris: http://localhost:9200
    username: #账号
    password: #密码
#讯飞AI 配置
ai:
  xunfei:
    appId:
    apiKey:
    apiSecret:
img:
  src: C:\Users\少年\Desktop\image\
  url: https://localhost/image/
#支付宝沙箱支付配置
alipay:
  appId: #appid
  privateKey: #私钥
  publicKey: #公钥
  signType: RSA2
  chatset: utf-8
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  returnUrl: #同步回调地址
  notifyUrl: #异步回调地址
